/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: im.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "im.grpc-c.h"

int
g_im__im_service__service_init (grpc_c_server_t *server)
{
    if (grpc_c_methods_alloc(server, 7))
        return 1;

    grpc_c_register_method(server, g_im__im_service__methods[0], 0, 0, &g_im__im_service__im_cmd_call_cb,
                         &g_im__im_cmd_request_packer, &g_im__im_cmd_request_unpacker, &g_im__im_cmd_request_free,
                         &g_im__im_cmd_response_packer, &g_im__im_cmd_response_unpacker, &g_im__im_cmd_response_free);

    grpc_c_register_method(server, g_im__im_service__methods[1], 0, 0, &g_im__im_service__im_ajust_call_cb,
                         &g_im__im_ajust_request_packer, &g_im__im_ajust_request_unpacker, &g_im__im_ajust_request_free,
                         &g_im__im_ajust_response_packer, &g_im__im_ajust_response_unpacker, &g_im__im_ajust_response_free);

    grpc_c_register_method(server, g_im__im_service__methods[2], 0, 0, &g_im__im_service__im_debug_call_cb,
                         &g_im__im_debug_request_packer, &g_im__im_debug_request_unpacker, &g_im__im_debug_request_free,
                         &g_im__im_debug_response_packer, &g_im__im_debug_response_unpacker, &g_im__im_debug_response_free);

    grpc_c_register_method(server, g_im__im_service__methods[3], 0, 0, &g_im__im_service__im_eeprom_read_cb,
                         &g_im__im_eeprom_request_packer, &g_im__im_eeprom_request_unpacker, &g_im__im_eeprom_request_free,
                         &g_im__im_eeprom_read_response_packer, &g_im__im_eeprom_read_response_unpacker, &g_im__im_eeprom_read_response_free);

    grpc_c_register_method(server, g_im__im_service__methods[4], 0, 0, &g_im__im_service__im_eeprom_write_cb,
                         &g_im__im_eeprom_request_packer, &g_im__im_eeprom_request_unpacker, &g_im__im_eeprom_request_free,
                         &g_im__im_eeprom_write_response_packer, &g_im__im_eeprom_write_response_unpacker, &g_im__im_eeprom_write_response_free);

    grpc_c_register_method(server, g_im__im_service__methods[5], 0, 0, &g_im__im_service__im_negative_pressure_adjust_call_cb,
                         &g_im__im_negative_pressure_request_packer, &g_im__im_negative_pressure_request_unpacker, &g_im__im_negative_pressure_request_free,
                         &g_im__im_negative_pressure_response_packer, &g_im__im_negative_pressure_response_unpacker, &g_im__im_negative_pressure_response_free);

    grpc_c_register_method(server, g_im__im_service__methods[6], 0, 0, &g_im__im_service__im_adjust_call_version_query_cb,
                         &g_im__im_version_query_request_packer, &g_im__im_version_query_request_unpacker, &g_im__im_version_query_request_free,
                         &g_im__im_version_query_response_packer, &g_im__im_version_query_response_unpacker, &g_im__im_version_query_response_free);

    return 0;
}

int
g_im__pc_service__service_init (grpc_c_server_t *server)
{
    if (grpc_c_methods_alloc(server, 3))
        return 1;

    grpc_c_register_method(server, g_im__pc_service__methods[0], 0, 0, &g_im__pc_service__ui_data_call_cb,
                         &g_im__im_ui_data_packer, &g_im__im_ui_data_unpacker, &g_im__im_ui_data_free,
                         &g_im__im_ui_data_response_packer, &g_im__im_ui_data_response_unpacker, &g_im__im_ui_data_response_free);

    grpc_c_register_method(server, g_im__pc_service__methods[1], 0, 0, &g_im__pc_service__ui_security_call_cb,
                         &g_im__im_security_data_packer, &g_im__im_security_data_unpacker, &g_im__im_security_data_free,
                         &g_im__im_ui_data_response_packer, &g_im__im_ui_data_response_unpacker, &g_im__im_ui_data_response_free);

    grpc_c_register_method(server, g_im__pc_service__methods[2], 0, 0, &g_im__pc_service__ui_upgrade_call_cb,
                         &g_im__im_device_upgrade_data_packer, &g_im__im_device_upgrade_data_unpacker, &g_im__im_device_upgrade_data_free,
                         &g_im__im_ui_data_response_packer, &g_im__im_ui_data_response_unpacker, &g_im__im_ui_data_response_free);

    return 0;
}
